[package]
name = "playfair"
version = "0.1.0"
edition = "2018"

[dependencies]
color-eyre = "~0.5"
futures = "~0.3"
serde = "~1.0"
serde_derive = "~1.0"
serde_json = "~1.0"
structopt = "~0.3"
thiserror = "~1.0"
tracing = "~0.1"
tracing-subscriber = "~0.2"
